#version 430 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba8, binding = 2) uniform image2D imgInput;
layout(r32f, binding = 0) uniform image2D imgOutput;

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    vec4 pixel = imageLoad(imgInput, texelCoord);

    float value = length(pixel) > 0.0 ? 1 : 0;

    imageStore(imgOutput, texelCoord, vec4(value));

}
